app:
  telegram-token: ${TELEGRAM_API_TOKEN}
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id: bot-messages
      mappings: edu.java.scrapper.dto.bot.LinkUpdateRequest:edu.java.bot.dto.request.LinkUpdateRequest
    topic-name: bot-updates
    trusted-packages: "*"
    dql-topic: bot-updates-dlq

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

rate-limit:
  token-count: 5
  refill-period: 30

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui

api:
  scrapper:
    base-url: http://localhost:8080
    retry:
      retry-policy: constant
      max-attempts: 3
      wait-duration: 2
      codes: INTERNAL_SERVER_ERROR, INSUFFICIENT_STORAGE, SERVICE_UNAVAILABLE, TOO_MANY_REQUESTS
